# Generated by Django 4.2.4 on 2023-08-12 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnswerSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default=None, max_length=255)),
                ("description", models.TextField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name="QuestionGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence_number", models.IntegerField(default=None)),
                ("title", models.CharField(default=None, max_length=255)),
                ("description", models.TextField(default=None)),
                ("help_tip", models.TextField(default=None)),
                ("source", models.CharField(default=None, max_length=2083)),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence_number", models.IntegerField(default=None)),
                ("title", models.CharField(default=None, max_length=255)),
                ("description", models.TextField(default=None)),
                ("help_tip", models.TextField(default=None)),
                ("source", models.TextField(default=None)),
                ("is_compulsory", models.BooleanField(default=None)),
                (
                    "answer_format",
                    models.CharField(
                        choices=[
                            ("boolean", "boolean"),
                            ("integer", "integer"),
                            ("string", "string"),
                        ],
                        default=None,
                        max_length=255,
                    ),
                ),
                (
                    "question_group_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="processes.questiongroup",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "int_answer",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                (
                    "string_answer",
                    models.TextField(blank=True, default=None, null=True),
                ),
                (
                    "boolean_answer",
                    models.BooleanField(blank=True, default=None, null=True),
                ),
                (
                    "answer_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="processes.answerset"
                    ),
                ),
                (
                    "question_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="processes.question"
                    ),
                ),
            ],
        ),
    ]
