# Generated by Django 4.2.4 on 2023-08-13 10:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('processes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='description',
            new_name='question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='source',
        ),
        migrations.RemoveField(
            model_name='question',
            name='title',
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_format',
            field=models.CharField(
                choices=[('boolean', 'boolean'), ('integer', 'integer'), ('string', 'string'), ('list', 'list')],
                default=None, max_length=255),
        ),
    ]
