# Generated by Django 4.2.3 on 2023-09-21 09:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("processes", "0002_rename_description_question_question_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="multiple_answer",
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
