# Generated by Django 3.2.21 on 2023-10-04 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0003_answer_multiple_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='int_answer',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
