# Generated by Django 4.2.3 on 2023-09-21 09:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staffAuth", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="staffauth",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="staffauth",
            name="last_login",
        ),
        migrations.RemoveField(
            model_name="staffauth",
            name="user_permissions",
        ),
        migrations.AlterField(
            model_name="staffauth",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
    ]
